### ISSUE TITLE
Invalid syntax on python 3.9

### ISSUE THREAD

**Issue by irv** [matteocacciola/fastapi_healthz#2]
Hi,

This syntax isn't supported on python 3.9

https://github.com/matteocacciola/fastapi_healthz/blob/08b0fd1352e9689b661068d93c53aef2e77c8997/fastapi_healthz/models.py#L17

I guess use `Optional` or bump the python-version to 3.10?

**Comment by matteocacciola** [comment]
fixed with commit fee93a69122a432fba73c3f04e8f43c6c95b3ef3. thank you
